# export.py

def generate_ansys_apdl(length, width, height, thickness, material_name, k_value):


    apdl_script = f"""! ANSYS APDL Script Generated by Suraksha-Awas
! Target: Thermal Finite Element Analysis (FEA)
! Material Selected: {material_name}

/PREP7 ! Enter preprocessor

!1. PARAMETERS
L = {length}   
W = {width}      
H = {height}      
THICK = {thickness}

!2. MATERIAL PROPERTIES
! Material ID 1
MP, KXX, 1, {k_value}

!3. GEOMETRY GENERATION
! Create the outer solid block
BLOCK, 0, L, 0, W, 0, H

! Create the inner hollow air space
BLOCK, THICK, L-THICK, THICK, W-THICK, THICK, H-THICK

! Subtract the inner block from the outer block to create hollow walls
! VSBV (Volume Subtract Volume)
VSBV, 1, 2

!4. MESHING PREP
VATT, 1, , 1
ESIZE, 0.1  ! Set element size for meshing
VMESH, ALL  ! Mesh the walls

FINISH
"""
    return apdl_script